# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # Configuration de la troisième machine pour le site web 2
  config.vm.define "web2" do |web2|
    web2.vm.box = "base"

    web2.vm.provision "shell", inline: <<-SHELL
      # Script de provisioning pour web2
      # Vous pouvez ajouter des commandes d'installation et de configuration ici
      sudo apt-get update
      sudo apt-get install -y apache2
      # Ajoutez d'autres commandes pour configurer votre site web ici
    SHELL
  end

end
